# Render Blueprint for AI-Powered Web Page Generator
# This file defines the deployment configuration for the Flask app

services:
  # Main Flask web service with Ollama running alongside
  - type: web
    name: ai-page-generator
    runtime: python
    plan: standard
    region: oregon
    buildCommand: ./setup.sh
    startCommand: ./run_server.sh
    envVars:
      - key: OLLAMA_API_URL
        value: http://localhost:11434/api/generate
      - key: OLLAMA_MODEL
        value: mistral
      - key: PYTHON_VERSION
        value: "3.9"
      - key: PORT
        value: "10000"
    healthCheckPath: /
    scaling:
      minInstances: 1
      maxInstances: 1 # Keep to 1 instance to avoid multiple Ollama/SD instances
    maxShutdownDelaySeconds: 600

# Environment groups for shared configuration
envVarGroups:
  - name: ai-settings
    envVars:
      - key: DIFFUSION_STEPS
        value: "100"
      - key: IMAGE_QUALITY
        value: "high"
      - key: MAX_PROMPT_LENGTH
        value: "200" 